[build]
  command = "npm --prefix web ci && npm --prefix web run build cd web
npm install video.js mpegts.js"
  publish = "web/out"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/api/proxy"
  function = "iptv-proxy"

[[redirects]]
  from = "/player"
  to = "/player/index.html"
  status = 200

[[redirects]]
  from = "/demo"
  to = "/demo/index.html"
  status = 200
